name: Update resource_list.json & memes.md

on:
  push:
    branches:
      - "main"
    paths:
      - "meme_generator/memes/**"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: poetry install

      - name: Install fonts
        run: |
          sudo apt install fonts-noto-cjk fonts-noto-color-emoji
          sudo locale-gen zh_CN zh_CN.UTF-8
          sudo update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
          sudo mkdir /usr/share/fonts/myfonts
          sudo cp resources/fonts/* /usr/share/fonts/myfonts/
          fc-cache -fv

      - name: Update resource_list.json
        run: poetry run python resources/update_list.py

      - name: Update memes.md
        run: poetry run python docs/update_doc.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
